import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import Event from "@/models/Event";
import { cookies } from "next/headers";
import jwt, { JwtPayload } from 'jsonwebtoken'
import { Resend } from 'resend'
import QRCode from 'qrcode'
import axios from "axios";
import api from "@/lib/axios";
import crypto from 'crypto'
import Ticket from "@/models/Ticket";
import TicketOrder from "@/models/TicketOrder";
import mongoose from "mongoose";
import { getUserFromCookie, verifyAuth } from "@/lib/auth";
import { StandType } from "@/types/components";
import { getBaseUrl } from "@/lib/utils";
import { summary } from "framer-motion/m";
import { redis } from "@/lib/redis";
import { populateTeamsForEvents } from "@/lib/populateEventTeams";
import { generateTickets } from "@/services/ticketService";


const resend = new Resend(process.env.RESEND_API_KEY)

// export async function POST(req: Request) {
//     // try {

//     // } catch (error: any) {

//     // }
//     NextResponse.json({
//         message: "Hello There!"
//     })

// }


async function SortTicketsForView(events: any[], tickets: any[], pendingOrders: any[] = []) {
    const ticketCount: Record<string, Record<string, number>> = {};
    const orphanedEventIds = new Set<string>();
    const pendingEventIds = new Set<string>();

    for (const order of pendingOrders) {
        const eventId = order.event?._id?.toString() || order.event?.toString();
        if (eventId) {
            pendingEventIds.add(eventId);
            const eventExists = events.some(e => e._id.toString() === eventId);
            if (!eventExists) orphanedEventIds.add(eventId);
        }
    }

    for (const ticket of tickets) {
        // Use the raw ID if the event is null (orphaned)
        const eventId = ticket.event?._id?.toString() || ticket.event?.toString();

        if (!eventId) continue;

        const stand = ticket.stand || "Regular";

        if (!ticketCount[eventId]) {
            ticketCount[eventId] = {};
        }

        ticketCount[eventId][stand] = (ticketCount[eventId][stand] || 0) + 1;

        // Check if this event exists in our list
        const eventExists = events.some(e => e._id.toString() === eventId);
        if (!eventExists) {
            orphanedEventIds.add(eventId);
        }
    }

    // Process existing events
    const extendedEvents = events.map(event => {
        const eventIdStr = event._id.toString();
        const plain = event.toObject ? event.toObject() : event;
        const matchedStands = ticketCount[eventIdStr];
        const transformedSummary = matchedStands ? Object.entries(matchedStands).map(([name, value]) => ({
            name,
            value
        })) : [];

        return {
            ...plain,
            transformedSummary,
            hasPendingOrders: pendingEventIds.has(eventIdStr)
        };
    });

    // Add orphaned events placeholders
    const orphanedGroups = Array.from(orphanedEventIds).map(eventId => {
        const matchedStands = ticketCount[eventId];
        const transformedSummary = matchedStands ? Object.entries(matchedStands).map(([name, value]) => ({
            name,
            value
        })) : [];

        return {
            _id: eventId,
            title: "Deleted Event",
            isOrphaned: true,
            transformedSummary,
            type: 'event', // Default to event for display
            hasPendingOrders: pendingEventIds.has(eventId)
        };
    });

    return [...extendedEvents, ...orphanedGroups];
}

export async function GET(req: Request) {
    try {
        await connectDB();
        await verifyAuth()

        // Get token from cookies
        const token = (await cookies()).get("token")?.value;

        if (!token) {
            return NextResponse.json(
                { error: "Unauthorized: No token provided" },
                { status: 401 }
            );
        }
        // Decode token
        const decoded = jwt.verify(token, process.env.JWT_SECRET!) as { id: string, userId: string };
        const userId = decoded.id;

        const cacheKey = `TICKETS_${userId}`

        // ───────────────────────────────────────────────────────────
        // Auto-generate any pending ticket orders BEFORE building
        // the response. This ensures users always see their purchased
        // tickets without needing to manually trigger generation.
        // ───────────────────────────────────────────────────────────
        const allPendingOrders = await TicketOrder.find({ user: userId, isGenerated: false }).lean();

        let totalAutoGenerated = 0;
        for (const order of allPendingOrders) {
            // Atomic lock: only the first request to claim this order will generate tickets
            const claimedOrder = await TicketOrder.findOneAndUpdate(
                { _id: order._id, isGenerated: false },
                { $set: { isGenerated: true } },
                { new: true }
            );

            if (!claimedOrder) continue; // Already claimed by a concurrent request

            try {
                const result = await generateTickets({
                    eventId: claimedOrder.event.toString(),
                    userId: claimedOrder.user?.toString() || userId,
                    batches: claimedOrder.tickets,
                    paymentReference: claimedOrder.reference ?? undefined,
                    isPaid: true,
                    generatedBy: 'online-sale'
                });
                totalAutoGenerated += result.totalGenerated;
            } catch (err) {
                // Roll back so it can be retried on next page visit
                await TicketOrder.findByIdAndUpdate(order._id, { $set: { isGenerated: false } });
                console.error(`[Auto-Generate] Failed for order ${order._id}:`, err);
            }
        }

        // Bust cache if we auto-generated anything
        if (totalAutoGenerated > 0) {
            await redis.del(cacheKey);
        }

        // Fetch events created by this user
        const tickets = await Ticket
            .find({ createdBy: userId })
            .lean()

        // Re-fetch pending orders (should now be empty or reduced after auto-generation)
        const pendingOrders = await TicketOrder.find({ user: userId, isGenerated: false }).lean()

        // Handle case where user has no events
        if (!tickets.length && !pendingOrders.length) {
            return NextResponse.json({
                message: "No tickets found for this user",
                tickets: [],
            });
        }

        const rawEvents = await Event.find({}).lean();
        const events = await populateTeamsForEvents(rawEvents);

        const eventsSortedWithTickets = await SortTicketsForView(events, tickets, pendingOrders)

        // Filter out empty summaries (no tickets for that event) OR if they don't have pending orders
        const validTickets = eventsSortedWithTickets.filter(group =>
            (group.transformedSummary && group.transformedSummary.length > 0) || group.hasPendingOrders
        );

        const updatedCache = await redis.set(cacheKey, validTickets)

        return NextResponse.json({
            message: "tickets fetched successfully",
            tickets: validTickets,
        });
    } catch (error) {
        //  console.error("Error fetching user events:", error);
        return NextResponse.json(
            { error: "Failed to fetch events" },
            { status: 500 }
        );
    }
}


export async function PrintTickets(data: any, eventId: string, isPaid: boolean, userIdOverride?: string, reference?: string) {
    const userId = userIdOverride || (await getUserFromCookie())?.id;
    if (!userId) throw new Error("User ID is required to print tickets");

    const result = await generateTickets({
        eventId,
        userId,
        batches: data,
        paymentReference: reference,
        isPaid,
        generatedBy: 'online-sale'
    });

    return result.tickets;
}

export async function POST(req: Request) {
    try {
        await connectDB();
        const data = await req.json();

        const user = await getUserFromCookie();
        if (!user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        let totalTickets = 0;
        data.ticketsToPurchase.forEach((ticket: any) => {
            totalTickets += (ticket.quantity || 0);
        });

        if (totalTickets > 400) {
            return NextResponse.json({
                message: "Bulk Tickets Order exceeds maximum limit"
            }, { status: 400 });
        }

        const result = await generateTickets({
            eventId: data.eventId,
            userId: user.id,
            batches: data.ticketsToPurchase,
            isPaid: true,
            generatedBy: 'online-sale'
        });

        return NextResponse.json({
            message: "Ticket created successfully",
            tickets: result.tickets
        }, { status: 200 });
    } catch (error: any) {
        return NextResponse.json(
            { error: "Failed to create ticket: " + error.message },
            { status: 500 }
        );
    }
}

export async function DELETE(req: Request) {
    try {
        await connectDB();
        const user = await getUserFromCookie();

        if (!user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const { searchParams } = new URL(req.url);
        const eventId = searchParams.get("eventId");

        if (!eventId) {
            return NextResponse.json({ error: "Event ID is required" }, { status: 400 });
        }

        const result = await Ticket.deleteMany({
            event: eventId,
            createdBy: user.id
        });

        try {
            await Promise.all([
                redis.del(`user_event_tickets:${user.id}:${eventId}`),
                redis.del(`TICKETS_${user.id}`)
            ]);
        } catch (cacheErr) {
            console.error("[Delete Event Tickets] Redis cache invalidation error:", cacheErr);
        }

        return NextResponse.json({
            success: true,
            message: `Deleted ${result.deletedCount} tickets successfully.`,
            deletedCount: result.deletedCount
        });

    } catch (error: any) {
        return NextResponse.json(
            { error: "Failed to delete tickets: " + error.message },
            { status: 500 }
        );
    }
}
