import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import { cookies } from "next/headers";
import Event from "@/models/Event";
import Ticket from "@/models/Ticket";
import TicketOrder from "@/models/TicketOrder";
import User from "@/models/User";
import jwt, { JwtPayload } from "jsonwebtoken";
import { redis } from "@/lib/redis";
import { populateTeamsForEvents } from "@/lib/populateEventTeams";
import { generateTickets } from "@/services/ticketService";


type Params = {
    params: Promise<{ hashToken: string }>;
};

/**
 * Auto-generates tickets for any ungenerated (pending) ticket orders belonging
 * to the requesting user for a given event. Uses an atomic findOneAndUpdate lock
 * to prevent duplicate generation from concurrent requests.
 */
async function autoGeneratePendingTickets(eventId: string, userId: string): Promise<number> {
    const pendingOrders = await TicketOrder.find({
        event: eventId,
        user: userId,
        isGenerated: false
    }).lean();

    if (pendingOrders.length === 0) return 0;

    let totalAutoGenerated = 0;

    for (const order of pendingOrders) {
        // Atomic lock: only the first request to claim this order will generate tickets
        const claimedOrder = await TicketOrder.findOneAndUpdate(
            { _id: order._id, isGenerated: false },
            { $set: { isGenerated: true } },
            { new: true }
        );

        if (!claimedOrder) {
            // Another concurrent request already claimed this order — skip
            continue;
        }

        try {
            const result = await generateTickets({
                eventId: claimedOrder.event.toString(),
                userId: claimedOrder.user?.toString() || userId,
                batches: claimedOrder.tickets,
                paymentReference: claimedOrder.reference ?? undefined,
                isPaid: true,
                generatedBy: 'online-sale'
            });

            totalAutoGenerated += result.totalGenerated;
        } catch (err) {
            // If generation fails, roll back the isGenerated flag so it can be retried
            await TicketOrder.findByIdAndUpdate(order._id, { $set: { isGenerated: false } });
            console.error(`[Auto-Generate] Failed to generate tickets for order ${order._id}:`, err);
        }
    }

    return totalAutoGenerated;
}

export async function GET(req: Request, { params }: Params) {
    try {
        await connectDB();
        const token = (await cookies()).get("token")?.value;

        if (!token) {
            return NextResponse.json(
                { error: "Unauthorized: No token provided" },
                { status: 401 }
            );
        }

        const decoded = jwt.verify(token, process.env.JWT_SECRET as string)
        if (typeof decoded === "string") {
            throw Error("Invalid token format");
        }

        const userId = (decoded as JwtPayload).id;

        // ✅ Await v directly — not props.context.v
        const { hashToken: eventId } = await params;

        // ───────────────────────────────────────────────────────────
        // Auto-generate any pending ticket orders BEFORE building
        // the response. This bridges the gap between payment and
        // ticket availability so users see their tickets immediately.
        // ───────────────────────────────────────────────────────────
        const autoGenCount = await autoGeneratePendingTickets(eventId, userId);

        // If we just generated tickets, bust the cache so the fresh data is returned
        const cacheKey = `user_event_tickets:${userId}:${eventId}`;
        if (autoGenCount > 0) {
            await redis.del(cacheKey);
        }

        // Retrieve from Upstash (only if we didn't just generate new tickets)
        if (autoGenCount === 0) {
            const cachedData: any = await redis.get(cacheKey);

            // Only serve cache if it contains actual tickets for this event.
            // If the cache was stored when there were 0 tickets, force a DB fetch.
            if (cachedData && cachedData?.tickets?.tickets?.length > 0) {
                return NextResponse.json(
                    { message: "Ticket found(cached)", response: cachedData },
                    { status: 200 }
                );
            }
        }

        // Cache Miss (or cache busted) - Retrieve from database
        const rawEvent = await Event.findById(eventId).lean();
        const event = await populateTeamsForEvents(rawEvent);
        const tickets = await Ticket.find({ createdBy: userId }).populate("event");
        await populateTeamsForEvents(tickets.map(t => t.event).filter(Boolean));
        const pendingOrders = await TicketOrder.find({ event: eventId, user: userId, isGenerated: false }).lean();

        const ticketCount: Record<string, Record<string, number>> = {};

        for (const ticket of tickets) {
            const ticketEventId = ticket.event?._id?.toString() || ticket.event?.toString();
            if (!ticketEventId) continue;

            const stand = ticket.stand || "Regular";

            if (!ticketCount[ticketEventId]) {
                ticketCount[ticketEventId] = {};
            }

            ticketCount[ticketEventId][stand] = (ticketCount[ticketEventId][stand] || 0) + 1;
        }

        const specificSummary = ticketCount[eventId] || {};
        const transformedSummary = Object.entries(specificSummary).map(([name, value]) => ({
            name,
            value
        }));

        const matchedTickets = tickets.filter(ticket => {
            const ticketEventId = ticket.event?._id?.toString() || ticket.event?.toString();
            return ticketEventId === eventId;
        });

        if (matchedTickets.length === 0 && pendingOrders.length === 0 && !event) {
            return NextResponse.json(
                { error: "Could not find event or tickets for this ID" },
                { status: 404 }
            );
        }

        const response = {
            event: event || { _id: eventId, title: "Deleted Event", isOrphaned: true, type: 'event' },
            tickets: {
                event: event || { _id: eventId },
                tickets: matchedTickets
            },
            summary: transformedSummary,
            pendingOrders
        }

        const updateCache = await redis.set(cacheKey, response, { ex: 1800 })

        return NextResponse.json(
            { message: "Ticket found", response },
            { status: 200 }
        );
    } catch (error) {
        console.error("Error:", error);
        return NextResponse.json(
            { error: "Internal Server Error" },
            { status: 500 }
        );
    }
}
